class AppSecrets{
  static const supabaseUrl='https://bffdckobwksejikiheal.supabase.co';
  static const supabaseAnonKey=
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZmRja29id2tzZWppa2loZWFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjE0Nzc4MDIsImV4cCI6MjAzNzA1MzgwMn0.C0KmPky2dmiJkyDR8Xgp_KyzRjf14_tXf1ihXQukZDQ';
}